### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by weijiawu** [Cyberist-Edgar/Google_Image_Searcher#1]
helllo, 您好，我用了您的代码，出了点bug，能看看这是啥问题吗
`<ipython-input-22-6f0399232e41> in upload_img_get_html(self, file)
     83         condition_2 = expected_conditions.visibility_of_element_located(
     84             (By.ID, "qbug"))
---> 85         WebDriverWait(driver, timeout=200, poll_frequency=0.5).until(
     86             condition_2)`

**Comment by weijiawu** [comment]
好像就是找不到这个“qbug”的按键在页面上。您那边是能正常运行的是吗
# 等待界面上出现upload an image

**Comment by junhaideng** [comment]
> helllo, 您好，我用了您的代码，出了点bug，能看看这是啥问题吗
> `<ipython-input-22-6f0399232e41> in upload_img_get_html(self, file) 83 condition_2 = expected_conditions.visibility_of_element_located( 84 (By.ID, "qbug")) ---> 85 WebDriverWait(driver, timeout=200, poll_frequency=0.5).until( 86 condition_2)`

使用的是哪一版本的代码？

**Comment by weijiawu** [comment]
v4，方便加个微信吗

**Comment by junhaideng** [comment]
> v4，方便加个微信吗

我加你吧

**Comment by weijiawu** [comment]
15167756092

**Comment by junhaideng** [comment]
网站结构发生改变，出现此类错误请自行修改元素查询path
