### ISSUE TITLE
下载的是小图，有办法下载原图（大图）吗？

### ISSUE THREAD

**Issue by fjpan2023** [Cyberist-Edgar/Google_Image_Searcher#2]
如题

**Comment by junhaideng** [comment]
你可以F12查看这些图片元素，它们都是base64编码出来的，解码出来的都是小图，如果想要获取大图，可以试试其他py库，比如PIL，[StackOverflow](https://stackoverflow.com/questions/273946/how-do-i-resize-an-image-using-pil-and-maintain-its-aspect-ratio) 这里也有个类似的问题，希望可以帮到你
