### ISSUE TITLE
某些镜像网站页面解析出错

### ISSUE THREAD

**Issue by yangn0** [Cyberist-Edgar/Google_Image_Searcher#6]
使用原网站时
https://www.google.com/searchbyimage/upload
正常

使用此镜像网站时，页面解析出错
https://shitu.paodekuaiweixinqun.com/searchbyimage/upload
![image](https://user-images.githubusercontent.com/35649701/150689144-c3d0c70e-4398-450c-b897-03f4f1f36635.png)
镜像网站对原网页结构做了更改，且难以写出普适性解析算法。

**Comment by junhaideng** [comment]
这是因为使用镜像网站的时候 Host 设置不对哈

**Comment by junhaideng** [comment]
改正：这是因为没有搜到相似的图片，当然 Host 不对也可能会导致获取到的源代码不对
